export interface MCQQuestion {
  id: string
  question: string
  options: string[]
  correctAnswer: number
  explanation: string
}

export const mcqQuestions: Record<string, MCQQuestion[]> = {
  maths: [
    {
      id: "math-mcq-1",
      question: "Solve for x: 2x + 5 = 13",
      options: ["x = 2", "x = 3", "x = 4", "x = 5"],
      correctAnswer: 2,
      explanation: 'Subtract 5 from both sides: 2x = 8. Divide by 2: x = 4. Correct answer is "x = 4".',
    },
    {
      id: "math-mcq-2",
      question: "What is the area of a circle with radius 5?",
      options: ["25π", "10π", "5π", "50π"],
      correctAnswer: 0,
      explanation: "Area of circle = πr². With r = 5: Area = π(5)² = 25π. This is the correct formula and calculation.",
    },
    {
      id: "math-mcq-3",
      question: "The sum of angles in a triangle is:",
      options: ["90°", "180°", "270°", "360°"],
      correctAnswer: 1,
      explanation:
        "The sum of all interior angles in any triangle is always 180°. This is a fundamental geometry property.",
    },
    {
      id: "math-mcq-4",
      question: "Solve: x² - 5x + 6 = 0",
      options: ["x = 1, 6", "x = 2, 3", "x = -2, -3", "x = 0, 5"],
      correctAnswer: 1,
      explanation: "Using factoring: (x-2)(x-3) = 0. Therefore x = 2 or x = 3. These are the correct solutions.",
    },
    {
      id: "math-mcq-5",
      question: "What is 15% of 200?",
      options: ["20", "25", "30", "35"],
      correctAnswer: 2,
      explanation: "Percentage calculation: 15% × 200 = 0.15 × 200 = 30. The answer is 30.",
    },
    {
      id: "math-mcq-6",
      question: "If a triangle has sides 3, 4, and 5, it is:",
      options: ["Obtuse", "Right", "Acute", "Isosceles"],
      correctAnswer: 1,
      explanation:
        "Since 3² + 4² = 9 + 16 = 25 = 5², this satisfies the Pythagorean theorem, making it a right triangle.",
    },
    {
      id: "math-mcq-7",
      question: "What is the value of 2³ × 2²?",
      options: ["2⁵", "2⁶", "2¹⁰", "4⁵"],
      correctAnswer: 0,
      explanation:
        "Using exponent rules: 2³ × 2² = 2^(3+2) = 2⁵ = 32. When multiplying powers with same base, add exponents.",
    },
    {
      id: "math-mcq-8",
      question: "The slope of line y = 2x + 3 is:",
      options: ["2", "3", "0", "1"],
      correctAnswer: 0,
      explanation: "In the form y = mx + b, m is the slope. Here m = 2, so the slope is 2.",
    },
    {
      id: "math-mcq-9",
      question: "What is log₁₀(100)?",
      options: ["1", "2", "10", "100"],
      correctAnswer: 1,
      explanation: "log₁₀(100) asks: 10 to what power equals 100? 10² = 100, so the answer is 2.",
    },
    {
      id: "math-mcq-10",
      question: "Find the mean of: 2, 4, 6, 8, 10",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      explanation: "Mean = Sum/Count = (2+4+6+8+10)/5 = 30/5 = 6. The mean is 6.",
    },
  ],
  science: [
    {
      id: "science-mcq-1",
      question: "What is the chemical formula for water?",
      options: ["H₂O", "O₂", "H₂", "HO₂"],
      correctAnswer: 0,
      explanation: "Water consists of 2 hydrogen atoms and 1 oxygen atom. The formula is H₂O.",
    },
    {
      id: "science-mcq-2",
      question: "What is the SI unit of force?",
      options: ["Joule", "Newton", "Watt", "Pascal"],
      correctAnswer: 1,
      explanation:
        "The Newton (N) is the SI unit of force. It is defined as kg⋅m/s². Joules measure energy, Watts measure power.",
    },
    {
      id: "science-mcq-3",
      question: "Photosynthesis produces:",
      options: ["Carbon dioxide", "Oxygen and glucose", "Nitrogen", "Water vapor"],
      correctAnswer: 1,
      explanation: "Photosynthesis: CO₂ + H₂O + Light → Glucose + O₂. The process produces glucose and oxygen.",
    },
    {
      id: "science-mcq-4",
      question: "The speed of light is approximately:",
      options: ["300 m/s", "300,000 km/s", "3,000 m/s", "30,000 km/s"],
      correctAnswer: 1,
      explanation:
        "The speed of light (c) is approximately 300,000 km/s or 3 × 10⁸ m/s. This is a fundamental constant.",
    },
    {
      id: "science-mcq-5",
      question: "Which organelle is the powerhouse of the cell?",
      options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
      correctAnswer: 2,
      explanation:
        "Mitochondria produce ATP, the energy currency of cells. This is why it's called the powerhouse of the cell.",
    },
    {
      id: "science-mcq-6",
      question: "What does DNA stand for?",
      options: ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Deoxyribose Nitrogen Acid", "Deoxyribonucleic Amino"],
      correctAnswer: 0,
      explanation:
        "DNA stands for Deoxyribonucleic Acid. It is the molecule that carries genetic instructions for life.",
    },
    {
      id: "science-mcq-7",
      question: "The process of water changing to ice is:",
      options: ["Condensation", "Freezing", "Sublimation", "Evaporation"],
      correctAnswer: 1,
      explanation:
        "Freezing is the process where liquid water turns into solid ice. This occurs at 0°C at standard pressure.",
    },
    {
      id: "science-mcq-8",
      question: "How many bones are in an adult human body?",
      options: ["186", "206", "226", "246"],
      correctAnswer: 1,
      explanation: "An adult human has approximately 206 bones. Babies are born with more, but some fuse as they grow.",
    },
    {
      id: "science-mcq-9",
      question: "What is the process of plants making food called?",
      options: ["Respiration", "Decomposition", "Photosynthesis", "Fermentation"],
      correctAnswer: 2,
      explanation: "Photosynthesis is the process where plants convert light energy into chemical energy (glucose).",
    },
    {
      id: "science-mcq-10",
      question: "Acids have a pH less than:",
      options: ["0", "7", "14", "10"],
      correctAnswer: 1,
      explanation: "The pH scale ranges from 0-14. Acids have pH < 7, neutral is 7, and bases have pH > 7.",
    },
  ],
  english: [
    {
      id: "english-mcq-1",
      question: "Which of the following is a noun?",
      options: ["Run", "Blue", "Happy", "Book"],
      correctAnswer: 3,
      explanation:
        '"Book" is a noun as it names a person, place, or thing. "Run" is a verb, "Blue" is an adjective, and "Happy" is an adjective.',
    },
    {
      id: "english-mcq-2",
      question: 'Identify the adverb in: "She runs quickly."',
      options: ["She", "runs", "quickly", "in"],
      correctAnswer: 2,
      explanation: '"Quickly" is an adverb modifying the verb "runs". It describes how she runs.',
    },
    {
      id: "english-mcq-3",
      question: '"The cat in the hat" - "in the hat" is a:',
      options: ["Noun phrase", "Prepositional phrase", "Verb phrase", "Adjective phrase"],
      correctAnswer: 1,
      explanation: '"In the hat" is a prepositional phrase starting with the preposition "in" and modifying "cat".',
    },
    {
      id: "english-mcq-4",
      question: "Which sentence is grammatically correct?",
      options: ["She go to school", "She goes to school", "She going to school", "She gone to school"],
      correctAnswer: 1,
      explanation:
        '"She goes to school" is correct. With third person singular (she), the verb takes an "-s" ending in present tense.',
    },
    {
      id: "english-mcq-5",
      question: '"As brave as a lion" is an example of:',
      options: ["Metaphor", "Simile", "Personification", "Irony"],
      correctAnswer: 1,
      explanation: 'This is a simile because it uses "as...as" to compare two things. Similes use "like" or "as".',
    },
    {
      id: "english-mcq-6",
      question: 'The subject of the sentence "The dog ran away" is:',
      options: ["ran", "away", "The dog", "The"],
      correctAnswer: 2,
      explanation: '"The dog" is the subject - the part of the sentence that performs the action (ran away).',
    },
    {
      id: "english-mcq-7",
      question: "Which word is a conjunction?",
      options: ["Beautiful", "And", "Quickly", "Under"],
      correctAnswer: 1,
      explanation:
        '"And" is a conjunction. It connects words, phrases, or clauses. The others are: adjective, adverb, and preposition.',
    },
    {
      id: "english-mcq-8",
      question: '"Life is a journey" is an example of:',
      options: ["Simile", "Metaphor", "Alliteration", "Hyperbole"],
      correctAnswer: 1,
      explanation: 'This is a metaphor because it directly compares two things without using "like" or "as".',
    },
    {
      id: "english-mcq-9",
      question: 'What is the past tense of "write"?',
      options: ["Wrote", "Written", "Writing", "Writes"],
      correctAnswer: 0,
      explanation: '"Wrote" is the simple past tense. "Written" is the past participle, used with "have" or "been".',
    },
    {
      id: "english-mcq-10",
      question: 'Identify the verb in: "The students study hard."',
      options: ["The", "students", "study", "hard"],
      correctAnswer: 2,
      explanation: '"Study" is the verb - the action word showing what the students do.',
    },
  ],
  social: [
    {
      id: "social-mcq-1",
      question: "Which civilization invented the wheel?",
      options: ["Egyptian", "Mesopotamian", "Indus Valley", "Chinese"],
      correctAnswer: 1,
      explanation:
        "The Mesopotamians (in modern-day Iraq) invented the wheel around 3500 BCE, which revolutionized transportation.",
    },
    {
      id: "social-mcq-2",
      question: "The Great Wall of China was built primarily to:",
      options: ["Trade", "Defend borders", "Store goods", "Celebrate"],
      correctAnswer: 1,
      explanation:
        "The Great Wall was built to defend against invasions from northern tribes and to control border trade.",
    },
    {
      id: "social-mcq-3",
      question: "Which is the largest continent by area?",
      options: ["Africa", "Europe", "Asia", "North America"],
      correctAnswer: 2,
      explanation: "Asia is the largest continent, covering about 44.5 million square kilometers.",
    },
    {
      id: "social-mcq-4",
      question: "The Nile River flows through which country primarily?",
      options: ["Sudan", "Egypt", "Uganda", "Ethiopia"],
      correctAnswer: 1,
      explanation:
        "The Nile flows through multiple countries, but Egypt is the primary civilization built on the Nile.",
    },
    {
      id: "social-mcq-5",
      question: "Ancient Rome was founded in:",
      options: ["753 BCE", "100 BCE", "500 CE", "1000 CE"],
      correctAnswer: 0,
      explanation: "Rome was traditionally founded in 753 BCE according to Roman legends and historical accounts.",
    },
    {
      id: "social-mcq-6",
      question: "The capital of Australia is:",
      options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
      correctAnswer: 2,
      explanation:
        "Canberra is the capital of Australia, built as a purpose-built capital city in the mid-20th century.",
    },
    {
      id: "social-mcq-7",
      question: "Which ocean is the largest?",
      options: ["Atlantic", "Indian", "Arctic", "Pacific"],
      correctAnswer: 3,
      explanation: "The Pacific Ocean is the largest, covering more area than all land on Earth combined.",
    },
    {
      id: "social-mcq-8",
      question: "The Renaissance began in:",
      options: ["Italy", "France", "Germany", "Spain"],
      correctAnswer: 0,
      explanation:
        "The Renaissance began in Italy during the 14th century, spreading to other European countries later.",
    },
    {
      id: "social-mcq-9",
      question: "Which mountain range is the highest?",
      options: ["Andes", "Himalayas", "Rocky Mountains", "Alps"],
      correctAnswer: 1,
      explanation: "The Himalayas are the highest mountain range, with Mount Everest reaching 8,849 meters.",
    },
    {
      id: "social-mcq-10",
      question: "Latitude lines run:",
      options: ["North-South", "East-West", "Diagonally", "Vertically"],
      correctAnswer: 1,
      explanation: "Latitude lines run East-West and measure distance from the equator. Longitude runs North-South.",
    },
  ],
  history: [
    {
      id: "history-mcq-1",
      question: "World War II ended in:",
      options: ["1943", "1944", "1945", "1946"],
      correctAnswer: 2,
      explanation: "World War II ended in 1945. Germany surrendered in May and Japan surrendered in August.",
    },
    {
      id: "history-mcq-2",
      question: "The French Revolution started in:",
      options: ["1789", "1799", "1809", "1819"],
      correctAnswer: 0,
      explanation: "The French Revolution began in 1789 with the storming of the Bastille on July 14.",
    },
    {
      id: "history-mcq-3",
      question: "Who was the first President of the USA?",
      options: ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "James Madison"],
      correctAnswer: 1,
      explanation: "George Washington was the first President, serving from 1789-1797.",
    },
    {
      id: "history-mcq-4",
      question: "The Renaissance was primarily a:",
      options: ["Military movement", "Religious movement", "Cultural movement", "Political movement"],
      correctAnswer: 2,
      explanation: "The Renaissance was a cultural movement emphasizing art, literature, science, and humanism.",
    },
    {
      id: "history-mcq-5",
      question: "The Industrial Revolution began in:",
      options: ["France", "Germany", "England", "America"],
      correctAnswer: 2,
      explanation: "The Industrial Revolution started in England around 1760, with steam engine innovations.",
    },
    {
      id: "history-mcq-6",
      question: "Martin Luther King Jr. gave his famous speech in:",
      options: ["1961", "1962", "1963", "1964"],
      correctAnswer: 2,
      explanation: '"I Have a Dream" was delivered on August 28, 1963, at the Lincoln Memorial.',
    },
    {
      id: "history-mcq-7",
      question: "The signing of the Magna Carta was in:",
      options: ["1115", "1215", "1315", "1415"],
      correctAnswer: 1,
      explanation: "The Magna Carta was signed in 1215, limiting the power of the English King.",
    },
    {
      id: "history-mcq-8",
      question: "Napoleon Bonaparte was from:",
      options: ["France", "Italy", "Spain", "Poland"],
      correctAnswer: 0,
      explanation: "Napoleon was a French military leader who rose to power during the French Revolution.",
    },
    {
      id: "history-mcq-9",
      question: "The Holocaust occurred during:",
      options: ["World War I", "World War II", "Cold War", "Korean War"],
      correctAnswer: 1,
      explanation: "The Holocaust was the systematic genocide of 6 million Jews by Nazi Germany during World War II.",
    },
    {
      id: "history-mcq-10",
      question: "The printing press was invented by:",
      options: ["Leonardo da Vinci", "Johannes Gutenberg", "Michelangelo", "Galileo Galilei"],
      correctAnswer: 1,
      explanation:
        "Johannes Gutenberg invented the printing press around 1440, revolutionizing the spread of information.",
    },
  ],
  accounts: [
    {
      id: "accounts-mcq-1",
      question: "Assets = Liabilities + ?",
      options: ["Revenue", "Expenses", "Equity", "Profit"],
      correctAnswer: 2,
      explanation: "The fundamental accounting equation is: Assets = Liabilities + Equity (or Owner's Capital).",
    },
    {
      id: "accounts-mcq-2",
      question: "A debit to an asset account:",
      options: ["Decreases it", "Increases it", "Has no effect", "Closes it"],
      correctAnswer: 1,
      explanation: "Assets increase with debits and decrease with credits in accounting.",
    },
    {
      id: "accounts-mcq-3",
      question: "Revenue is recorded when:",
      options: ["Cash is received", "Invoice is sent", "Service is provided", "Expense is paid"],
      correctAnswer: 2,
      explanation:
        "Under accrual accounting, revenue is recognized when earned (service provided), not when cash is received.",
    },
    {
      id: "accounts-mcq-4",
      question: "Which account is a liability?",
      options: ["Cash", "Equipment", "Accounts Payable", "Sales"],
      correctAnswer: 2,
      explanation: "Accounts Payable is a liability because it represents money the business owes to suppliers.",
    },
    {
      id: "accounts-mcq-5",
      question: "Depreciation is:",
      options: ["A liability", "An expense", "An asset", "Revenue"],
      correctAnswer: 1,
      explanation: "Depreciation is an expense representing the decrease in value of fixed assets over time.",
    },
    {
      id: "accounts-mcq-6",
      question: "The trial balance is used to:",
      options: ["Record transactions", "Check accuracy", "Prepare statements", "Collect payments"],
      correctAnswer: 1,
      explanation: "A trial balance lists all accounts to verify that debits equal credits in the accounting system.",
    },
    {
      id: "accounts-mcq-7",
      question: "Rent paid in advance is classified as:",
      options: ["Expense", "Prepaid expense", "Liability", "Equity"],
      correctAnswer: 1,
      explanation:
        "Prepaid expense (like advance rent) is an asset until the period is used, then it becomes an expense.",
    },
    {
      id: "accounts-mcq-8",
      question: "Working capital is calculated as:",
      options: ["Assets - Liabilities", "Current Assets - Current Liabilities", "Revenue - Expenses", "Cash - Debt"],
      correctAnswer: 1,
      explanation: "Working capital = Current Assets - Current Liabilities, measuring short-term financial health.",
    },
    {
      id: "accounts-mcq-9",
      question: "An income statement shows:",
      options: ["Financial position", "Cash flow", "Profitability", "Asset value"],
      correctAnswer: 2,
      explanation: "Income statement (Profit & Loss) shows revenues, expenses, and profit/loss over a period.",
    },
    {
      id: "accounts-mcq-10",
      question: "Goodwill is classified as:",
      options: ["Liability", "Intangible asset", "Current asset", "Expense"],
      correctAnswer: 1,
      explanation:
        "Goodwill is an intangible asset representing the premium paid for a business above fair market value.",
    },
  ],
  commerce: [
    {
      id: "commerce-mcq-1",
      question: "Commerce primarily deals with:",
      options: ["Production", "Exchange of goods", "Agriculture", "Manufacturing"],
      correctAnswer: 1,
      explanation: "Commerce involves the exchange and distribution of goods and services.",
    },
    {
      id: "commerce-mcq-2",
      question: "Which is a form of business organization?",
      options: ["Government", "School", "Partnership", "Hospital"],
      correctAnswer: 2,
      explanation: "A partnership is a business organization with two or more owners sharing profits and liabilities.",
    },
    {
      id: "commerce-mcq-3",
      question: "Marketing includes:",
      options: ["Only advertising", "Product, Price, Place, Promotion", "Only sales", "Only distribution"],
      correctAnswer: 1,
      explanation: "Marketing includes the 4 Ps: Product, Price, Place (distribution), and Promotion.",
    },
    {
      id: "commerce-mcq-4",
      question: "Which is a direct tax?",
      options: ["Sales tax", "Income tax", "Excise tax", "VAT"],
      correctAnswer: 1,
      explanation: "Income tax is a direct tax paid directly to the government by the taxpayer.",
    },
    {
      id: "commerce-mcq-5",
      question: "Consumer protection is important for:",
      options: ["Sellers only", "Buyers and sellers", "Government only", "Manufacturers"],
      correctAnswer: 1,
      explanation: "Consumer protection balances interests between buyers and sellers, ensuring fair trade.",
    },
    {
      id: "commerce-mcq-6",
      question: "Export means:",
      options: ["Buying goods", "Selling domestically", "Selling to foreign countries", "Storing goods"],
      correctAnswer: 2,
      explanation: "Export is sending goods to foreign countries for sale.",
    },
    {
      id: "commerce-mcq-7",
      question: "A warehouse is used for:",
      options: ["Manufacturing", "Storing goods", "Selling", "Advertising"],
      correctAnswer: 1,
      explanation: "Warehouses store goods before distribution to retailers or consumers.",
    },
    {
      id: "commerce-mcq-8",
      question: "Inflation means:",
      options: ["Decrease in prices", "Increase in prices", "Economic growth", "Currency appreciation"],
      correctAnswer: 1,
      explanation: "Inflation is the sustained increase in general price levels in an economy.",
    },
    {
      id: "commerce-mcq-9",
      question: "E-commerce includes:",
      options: ["Physical stores", "Online buying and selling", "Warehousing", "Transportation"],
      correctAnswer: 1,
      explanation: "E-commerce (electronic commerce) involves buying and selling through electronic platforms.",
    },
    {
      id: "commerce-mcq-10",
      question: "Customer service is important because:",
      options: ["It reduces costs", "It builds loyalty", "It increases taxes", "It decreases quality"],
      correctAnswer: 1,
      explanation: "Good customer service builds customer loyalty, leading to repeat business and referrals.",
    },
  ],
  economics: [
    {
      id: "economics-mcq-1",
      question: "Economics is the study of:",
      options: ["Money", "Scarcity and choice", "Banking", "Investment"],
      correctAnswer: 1,
      explanation: "Economics studies how societies manage scarce resources and make allocation choices.",
    },
    {
      id: "economics-mcq-2",
      question: "When supply exceeds demand, price:",
      options: ["Increases", "Decreases", "Stays constant", "Doubles"],
      correctAnswer: 1,
      explanation: "When supply exceeds demand (surplus), prices decrease to reach equilibrium.",
    },
    {
      id: "economics-mcq-3",
      question: "GDP measures:",
      options: ["Population", "Total output value", "Unemployment", "Inflation"],
      correctAnswer: 1,
      explanation: "GDP (Gross Domestic Product) measures the total monetary value of goods and services.",
    },
    {
      id: "economics-mcq-4",
      question: "Opportunity cost is:",
      options: ["Production cost", "Value of next best alternative", "Marketing cost", "Fixed cost"],
      correctAnswer: 1,
      explanation: "Opportunity cost is the benefit of the next best alternative foregone when making a choice.",
    },
    {
      id: "economics-mcq-5",
      question: "Which economic system relies on market forces?",
      options: ["Command", "Capitalism", "Socialism", "Feudalism"],
      correctAnswer: 1,
      explanation: "Capitalism relies on market forces (supply/demand) to allocate resources.",
    },
    {
      id: "economics-mcq-6",
      question: "Inflation is caused by:",
      options: ["Stable prices", "Increased money supply", "Low demand", "Falling prices"],
      correctAnswer: 1,
      explanation: "Inflation often results from an increased money supply relative to available goods.",
    },
    {
      id: "economics-mcq-7",
      question: "Unemployment benefits are part of:",
      options: ["Revenue", "Investment", "Welfare program", "Tax"],
      correctAnswer: 2,
      explanation: "Unemployment benefits are welfare programs providing income to unemployed individuals.",
    },
    {
      id: "economics-mcq-8",
      question: "Comparative advantage theory suggests:",
      options: ["No trade", "Trade benefits all", "Trade harms developing countries", "Trade is equal"],
      correctAnswer: 1,
      explanation:
        "Comparative advantage suggests countries benefit from specializing in what they do relatively well.",
    },
    {
      id: "economics-mcq-9",
      question: "A recession is defined as:",
      options: ["Rapid growth", "Two consecutive quarters of negative growth", "Inflation", "High employment"],
      correctAnswer: 1,
      explanation: "A recession is technically two consecutive quarters of declining GDP.",
    },
    {
      id: "economics-mcq-10",
      question: "The central bank controls:",
      options: ["Taxes", "Spending", "Monetary policy", "Wages"],
      correctAnswer: 2,
      explanation: "Central banks control monetary policy including interest rates and money supply.",
    },
  ],
}
